name: nuget
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 1-7 * 6"

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 defaults
        uses: devlooped/actions-bot@v1
        with:
          name: ${{ secrets.BOT_NAME }}
          email: ${{ secrets.BOT_EMAIL }}
          gh_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 🤘 checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}
          
      - name: ⚙ sponsors
        shell: pwsh
        run: |
          dotnet tool update -g dotnet-sponsor
          $owners = gc owners.json | convertfrom-json
          foreach ($owner in $owners) {
            '${{ secrets.DEVLOOPED_TOKEN }}' | sponsor nuget --tos --oss-only false --with-token --force --owner $owner
          }
          # global stats for all packages
          '${{ secrets.DEVLOOPED_TOKEN }}' | sponsor nuget --tos --force --with-token

      - name: ⬆️ commit
        run: |
          git add *.json
          (git commit -m "🖉 Update OSS contributors stats" && git push) || echo "Done"