name: nuget
on:
  workflow_dispatch:
    inputs:
      global:
        type: choice
        description: Collect General Stats
        required: true
        options: 
        - $true
        - $false
      owner:
        description: Collect Specific Owner Stats

  schedule:
    - cron: "0 2 1 * *"

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 defaults
        uses: devlooped/actions-bot@v1
        with:
          name: ${{ secrets.BOT_NAME }}
          email: ${{ secrets.BOT_EMAIL }}
          gh_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 🤘 checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}
          
      - name: ⚙ sponsors
        shell: pwsh
        env:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          dotnet tool update -g dotnet-sponsor
          $owners = gc owners.json | convertfrom-json
          if ('${{ github.event.inputs.owner }}') {
            $owners = @('${{ github.event.inputs.owner }}')
          }
          foreach ($owner in $owners) {
            '${{ env.token }}' | sponsor nuget --tos --exceptions --oss-only false --with-token --force --owner $owner
          }
          # global stats for all packages
          if (${{ github.event.inputs.global || '$true' }}) {
            '${{ env.token }}' | sponsor nuget --tos --exceptions --force --with-token
          }

      - name: ⬆️ commit
        run: |
          git add *.json
          git commit -m "🖉 Update OSS contributors stats"
          git pull
          git push